name: Deploy Senha Rápida to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto Angular
        run: npm run build -- --configuration production --base-href "/senha-rapida/"

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/senha-rapida
